### ISSUE TITLE
Temp USB WAN using a RPi 3B+

### ISSUE THREAD

**Issue by droideggs** [hazarjast/5g_rpi4_build#2]
I have a RPi 3B+ but its using a BCM2837B0 not a BCM2711. Would the same ipk files you listed work? I tried looking under https://downloads.openwrt.org/releases/22.03.3/targets/ but couldn't find a BCM2837B0 equivalent files. 

Thanks and looking foward to using your guide

**Comment by hazarjast** [comment]
I don’t have a 3B+ but that believe it is Broadcom Cortex A53 based. That should be under the OpenWRT BCM2710 target, so packages (.ipk files) for it under 22.03.3 would be here: https://downloads.openwrt.org/releases/22.03.3/targets/bcm27xx/bcm2710/packages/

Hope this helps :)

Be aware that with 22.x builds there’s some pretty big changes with the move to nftables vs iptables which I’ve not tested in the scope of this project so it may require different steps for TTL mangle on the modem interface etc.

**Comment by hazarjast** [comment]
Believe the link to the BCM2710 target package for your desired OpenWRT version should get you rolling on the RPi 3B+.
